### PR TITLE
Collective fix for new Reddit features as of July 2020

### LINKED ISSUE #15: Adding /overview to user profiles.
It would be really useful if it could add /overview in user profiles.
[Example](https://old.reddit.com/user/snow344/overview)

### LINKED ISSUE #29: Fix for https://www.reddit.com/rpan
https://old.reddit.com/rpan/* doesn't exist. https://www.reddit.com/rpan/* needs to be excluded.

### LINKED ISSUE #32: Whitelist privacy settings page
Hello, at the moment https://new.reddit.com/settings/privacy does not have an equivalent page https://old.reddit.com/settings/privacy and from what I've seen these options are just not available in the old reddit settings.
Regex for url matching should be 
`details.url.match(/^https?:\/\/(www\.)*reddit.com\/settings\/privacy/)`

### LINKED ISSUE #33: Reddit image galleries are broken
As of today, July 15th, 2020, [Reddit natively supports image galleries](https://old.reddit.com/r/announcements/comments/hrrh23/now_you_can_make_posts_with_multiple_images/). These galleries, however, do not work with the `old.reddit.com` subdomain and instead show a "page not found" screen. People in the comments section have already complained of the link being dead for them, presumably because they use Old Reddit Redirect. If Imgur galleries are anything to go by, these new galleries will soon constitute a major part of all image posts.

Are there any plans to add support for this new feature? I would be happy to contribute relevant code, but my previous pull request #5 was struck down as "not lightweight enough".

### PR DESCRIPTION
**Pull request by Lachcim**
This pull request introduces redirection exceptions for Reddit features introduced over the past two years. It also includes minor code refactoring.

Excluded subdomains are `blog`, `mod`, `oauth` and `out`. Excluded pathnames are `/chat`, `/gallery`, `/poll`, `/rpan`, `/settings` and `/topics`. This fixes #33, #32 and #29.

Some of the code is derived from pull request #5. With regard to #33, however, I've decided against reimplementing the user profile fix because the underlying issue has since been fixed by Reddit. This renders #15 irrelevant.

I've bumped the semantic version number to 1.1.5

Fixes #33
Fixes #32
Fixes #29
Closes #15

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Let me know when you want me to review it

**Comment by Lachcim** [comment]
The pull request is ready to be merged.

File: background.js [hunk 1]
```diff
@@ -1,16 +1,31 @@
 const oldReddit = "https://old.reddit.com";
+const excludedSubdomains = [
+  "blog.reddit.com",
+  "mod.reddit.com",
+  "oauth.reddit.com",
+  "out.reddit.com"];
```
Comment (tom-james-watson) [inline background.js:6]: This doesn't do anything - the `chrome.webRequest.onBeforeRequest.addListener(` callback is only called when one of the urls listed in `urls` below is matched. Note that I have just merged https://github.com/tom-james-watson/old-reddit-redirect/pull/31 which adds `amp.reddit.com`.

So yeah - basically you don't need this `excludedSubdomains` logic.

File: background.js [hunk 2]
```diff
@@ -1,16 +1,31 @@
...
+const excludedPaths = [
+  "/chat",
```
Comment (tom-james-watson) [inline background.js:8]: https://old.reddit.com/chat loads absolutely fine

File: background.js (hunk 1 above)
Comment (tom-james-watson) [reply background.js:6]: It looks like you've copied this from https://github.com/tom-james-watson/old-reddit-redirect/pull/5 but you haven't updated the urls to `"*://*.reddit.com/*"` to compensate.

Comment (tom-james-watson) [reply background.js:6]: That change would only be necessary if we want to be able to redirect certain old.reddit.com urls to reddit.com urls, like you had originally suggested should be done for `user/overview`.

File: background.js (hunk 2 above)
Comment (Lachcim) [reply background.js:8]: My bad, it was a connection issue

File: manifest.json [hunk 3]
```diff
@@ -1,7 +1,7 @@
 {
   "name": "Old Reddit Redirect",
   "description": "Ensure Reddit always loads the old design",
-  "version": "1.1.4",
+  "version": "1.1.5",
```
Comment (tom-james-watson) [inline manifest.json:4]: Let's bump to 1.2.0 as we're adding some new features
